# Generated by Django 3.0.8 on 2020-07-06 10:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sup_name', models.CharField(max_length=50)),
                ('sup_contact', models.CharField(max_length=10)),
                ('sup_email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subCat_name', models.CharField(max_length=30)),
                ('cat_rel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=50)),
                ('item_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('item_quantity', models.DecimalField(decimal_places=2, max_digits=5)),
                ('brand_rel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Brand')),
                ('cat_rel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Category')),
                ('subCat_rel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.SubCategory')),
                ('sup_rel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Supplier')),
            ],
        ),
    ]
